{-# LANGUAGE Trustworthy #-}

-- |
-- Copyright: 2026 Greg Pfeil
-- License: AGPL-3.0-only WITH Universal-FOSS-exception-1.0 OR LicenseRef-proprietary
--
-- Checks that the "NoRecursion" plugin rejects the recursion it’s meant to
-- reject.
--
-- A plugin can only be loaded from a registered package, so the invocation is
-- generated by @Setup.hs@ into `Build_fixtures` rather than discovered here:
-- what these fixtures are compiled against is the unit this build produced, not
-- whichever registration a search happened to reach first.
module Main
  ( main,
  )
where

import safe "base" Control.Applicative (pure)
import safe "base" Control.Category ((.))
import safe "base" Data.Bool (Bool (True), not, (&&))
import safe "base" Data.Foldable (traverse_)
import safe "base" Data.Function (($))
import safe "base" Data.Functor (fmap, (<$>))
import safe "base" Data.Kind (Type)
import safe "base" Data.List (filter, intercalate, isInfixOf, null)
import safe "base" Data.Maybe (Maybe (Just, Nothing))
import safe "base" Data.Semigroup ((<>))
import safe "base" Data.String (String, unwords)
import safe "base" System.Exit (ExitCode (ExitFailure, ExitSuccess))
import safe "base" System.IO (FilePath, IO, putStrLn)
import "directory" System.Directory
  ( createDirectoryIfMissing,
    getTemporaryDirectory,
  )
import safe "filepath" System.FilePath ((</>))
import "hspec" Test.Hspec
  ( Spec,
    describe,
    expectationFailure,
    hspec,
    it,
    runIO,
  )
import "process" System.Process (readProcessWithExitCode)
import safe "this" Build_fixtures qualified as Build

-- | What a fixture is supposed to do when the plugin sees it.
type Expectation :: Type
data Expectation
  = -- | The module must compile.
    Compiles
  | -- | Compilation must fail with a recursion report, mentioning every string
    --   in the first list and none of the strings in the second.
    Rejected [String] [String]
  | -- | Compilation must fail before any recursion is looked for — over a
    --   malformed plugin option, say — with a message mentioning every string
    --   given.
    Invalid [String]

-- | Where the fixtures live, relative to the package directory.
fixtureDir :: FilePath
fixtureDir = "tests" </> "fixtures"

-- | What a rejection must never look like. A plugin that throws where GHC
--   expects an error reports a panic and asks for a bug report, which is a
--   different — and much worse — outcome than rejecting the module.
panicky :: [String]
panicky = ["panic", "internal error"]

-- | Every recursion report starts with this.
rejectionPrefix :: String
rejectionPrefix = "encountered recursion"

spec :: Spec
spec = describe "the fixtures" do
  outDir <- runIO $ (</> "no-recursion-fixtures") <$> getTemporaryDirectory
  runIO $ createDirectoryIfMissing True outDir

  -- Reported unconditionally, so that a log makes it plain which build of the
  -- plugin these results are about.
  runIO . putStrLn . unwords $ "compiling the fixtures with" : Build.ghc : Build.flags

  -- The plugin is loaded from the fixture’s own `OPTIONS_GHC` pragma.
  it "rejects a top-level recursive binding" $
    (outDir, "TopLevelRec.hs", []) `shouldResultIn` Rejected ["recDef"] panicky

  -- Loaded from the command line instead, which is the path a @ghc-options@
  -- field takes. "PlainRec" carries no pragma, so if this flag were ignored the
  -- module would compile and the case would fail.
  it "rejects one whose plugin came from the command line" $
    (outDir, "PlainRec.hs", ["-fplugin", "NoRecursion"])
      `shouldResultIn` Rejected ["recDef"] panicky

  -- The desugarer invents different binders at different optimisation levels,
  -- so the two have to be checked to agree.
  it "rejects the same binding at -O0" $
    (outDir, "TopLevelRec.hs", ["-O0"]) `shouldResultIn` Rejected ["recDef"] panicky

  it "rejects the same binding at -O" $
    (outDir, "TopLevelRec.hs", ["-O"]) `shouldResultIn` Rejected ["recDef"] panicky

  it "rejects an option name it does not know" $
    (outDir, "Ok.hs", ["-fplugin-opt", "NoRecursion:no-such-option"])
      `shouldResultIn` Invalid ["unknown plugin option", "no-such-option"]

  it "rejects an option given without its value" $
    (outDir, "Ok.hs", ["-fplugin-opt", "NoRecursion:ignoredDecls"])
      `shouldResultIn` Invalid
        ["was expecting a List but had no value", "ignoredDecls"]

  it "obeys the later flag when it turns allowRecursion off" $
    ( outDir,
      "TopLevelRec.hs",
      [ "-fplugin-opt",
        "NoRecursion:allowRecursion:true",
        "-fplugin-opt",
        "NoRecursion:allowRecursion:false"
      ]
    )
      `shouldResultIn` Rejected ["recDef"] panicky

  it "obeys the later flag when it turns allowRecursion on" $
    ( outDir,
      "TopLevelRec.hs",
      [ "-fplugin-opt",
        "NoRecursion:allowRecursion:false",
        "-fplugin-opt",
        "NoRecursion:allowRecursion:true"
      ]
    )
      `shouldResultIn` Compiles

  -- The fixture has @`allowRecursion:true@ and comes after this flag, so the
  -- pragma has to win.
  it "lets a fixture’s own pragma beat an earlier command-line flag" $
    ( outDir,
      "OptionPrecedence.hs",
      ["-fplugin-opt", "NoRecursion:allowRecursion:false"]
    )
      `shouldResultIn` Compiles

  -- The same two orderings, written the way a flag with a value is written
  -- everywhere else: `name=value`.
  it "reads a value written with =, turning allowRecursion off" $
    ( outDir,
      "TopLevelRec.hs",
      [ "-fplugin-opt",
        "NoRecursion:allowRecursion=true",
        "-fplugin-opt",
        "NoRecursion:allowRecursion=false"
      ]
    )
      `shouldResultIn` Rejected ["recDef"] panicky

  it "reads a value written with =, turning allowRecursion on" $
    ( outDir,
      "TopLevelRec.hs",
      [ "-fplugin-opt",
        "NoRecursion:allowRecursion=false",
        "-fplugin-opt",
        "NoRecursion:allowRecursion=true"
      ]
    )
      `shouldResultIn` Compiles

-- | The test-suite entry point.
--
-- @since 0.5.0
main :: IO ()
main = hspec $ describe "NoRecursion" spec

-- | Compiles a fixture, discarding its output.
--
--   @-fforce-recomp@ is needed because the plugin is pure, and GHC then ignores
--   changes to the plugin itself.
compileFixture ::
  FilePath -> [String] -> FilePath -> IO (ExitCode, String, String)
compileFixture outDir extra name =
  readProcessWithExitCode
    Build.ghc
    ( extra
        <> Build.flags
        <> [ "-c",
             "-fforce-recomp",
             "-outputdir",
             outDir,
             "-v0",
             fixtureDir </> name
           ]
    )
    ""

-- | Compiles a fixture and asserts on what happened, so that a case reads the
--   way an hspec expectation reads. The left-hand side is where to put the
--   compiler’s output, the fixture, and whatever flags it needs beyond the ones
--   every fixture gets.
shouldResultIn ::
  (FilePath, FilePath, [String]) ->
  Expectation ->
  IO ()
shouldResultIn (outDir, name, extra) =
  checkFixture outDir name extra

-- | Compiles a fixture and reports every way in which it did not do what it was
--   supposed to.
checkFixture ::
  FilePath ->
  FilePath ->
  [String] ->
  Expectation ->
  IO ()
checkFixture outDir name extra expectation = do
  (code, _out, err) <- compileFixture outDir extra name
  traverse_ expectationFailure $ case (code, required expectation) of
    (ExitSuccess, Nothing) -> Nothing
    (ExitFailure _, Nothing) ->
      Just $ name <> ": should have compiled, but the plugin rejected it:\n" <> err
    (ExitSuccess, Just _) ->
      Just $ name <> ": should have been rejected, but it compiled cleanly."
    (ExitFailure _, Just (wanted, unwanted)) ->
      let missing = filter (not . (`isInfixOf` err)) wanted
          spurious = filter (`isInfixOf` err) unwanted
       in if null missing && null spurious
            then Nothing
            else
              Just $
                name
                  <> ": was rejected, but"
                  <> ( if null missing
                         then ""
                         else " the message never mentions " <> list missing <> ";"
                     )
                  <> ( if null spurious
                         then ""
                         else " the message mentions " <> list spurious <> ";"
                     )
                  <> "\n"
                  <> err
  where
    -- Error message pattern matching.
    required = \case
      Compiles -> Nothing
      Rejected wanted unwanted -> pure (rejectionPrefix : wanted, unwanted)
      Invalid wanted -> pure (wanted, panicky)
    list = intercalate ", " . fmap (\s -> "‘" <> s <> "’")
